export const SIGN_IN_SEND_OTP_REQUESTED = "SIGN_IN_SEND_OTP_REQUESTED";
export const SIGN_IN_SEND_OTP_SUCCESS = "SIGN_IN_SEND_OTP_SUCCESS";
export const SIGN_IN_SEND_OTP_FAILURE = "SIGN_IN_SEND_OTP_FAILURE";

export const SAVE_TASKS    = "SAVE_TASKS";
export const SAVE_TASK     = "SAVE_TASK";

export const DASHBOARD_MODE= "DASHBOARD_MODE";

export const SAVE_PRODUCTS = "SAVE_PRODUCTS";